#!/bin/bash
echo "---------------------------------------------------------------------------------------"
echo "Platter: Data is stored on magnetic or optical disk platters."
echo "Head: Data is read by heads."
echo "Tracks: Data is written in concentric circles called tracks."
echo "Sectors: Tracks are divided into 512 byte sectors"
echo "---------------------------------------------------------------------------------------"
echo "********************************IDE/ATA or SCSI****************************************"
echo "ATA: ATA Controller allows 2 devices per bus."
echo "SCSI: Allows more than 2 devices. Each device gets a uniques scsi id."
echo "---------------------------------------------------------------------------------------"
echo "BLOCK DEVICE: HDD have an abstraction layer called block device."
echo "SSD: Is a block device without moving parts."
echo "---------------------------------------------------------------------------------------"
echo "********************************DEVICE NAMING******************************************"
echo "ata: All ata drives on system will start with /dev/hd followed by unit letter."
echo "scsi: Starts with /dev/sd followed by unit letter."
echo "---------------------------------------------------------------------------------------"
