#!/bin/bash
echo "All processes have a process id or PID"
echo "Every process has a parent process(PPID)"
echo "init/systemd is the first process that will start and has a process ID 1"
echo -e "To get the current process id run(echo \$\$)"
echo "My Current process ID is `echo $$`"
echo "------------------------------------------------------------------------------------------------------"
echo "Daemon:Processes that start at system startup and keep running forever are called daemon processes."
echo "Zombie: Processes that are killed but still exist in process table.(or dead process) "
echo "------------------------------------------------------------------------------------------------------"
echo "Parent Process ID: (echo \$PPID)"
echo "`echo $PPID`"
echo "------------------------------------------------------------------------------------------------------"
echo "To find process id using process name:(echo pidof <process-name>)"
echo "Using pidof: `pidof bash`"
echo "------------------------------------------------------------------------------------------------------"
echo "----------------------------------------fork and exec-------------------------------------------------"
echo "fork: identical copy; A fork process starts another process in 2 phases:"
echo "1. Created a fork of itself.
2. Forked process executes an exec to replace the forked process with the target child process."
echo "------------------------------------------------------------------------------------------------------"
echo "exec: executes a process without forking a new process"
echo "------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------------------------------"
