#!/bin/bash
echo "All processes have a process id or PID"
echo "Every process has a parent process(PPID)"
echo "init/systemd is the first process that will start and has a process ID 1"
echo -e "To get the current process id run(echo \$\$)"
echo "My Current process ID is `echo $$`"
echo "------------------------------------------------------------------------------------------------------"
echo "Daemon:Processes that start at system startup and keep running forever are called daemon processes."
echo "Zombie: Processes that are killed but still exist in process table.(or dead process) "
echo "------------------------------------------------------------------------------------------------------"
echo "Parent Process ID: (echo \$PPID)"
echo "`echo $PPID`"
echo "------------------------------------------------------------------------------------------------------"
echo "To find process id using process name:(echo pidof <process-name>)"
echo "Using pidof: `pidof bash`"
echo "------------------------------------------------------------------------------------------------------"
echo "----------------------------------------fork and exec-------------------------------------------------"
echo "fork: identical copy; A fork process starts another process in 2 phases:"
echo "1. Created a fork of itself.
2. Forked process executes an exec to replace the forked process with the target child process."
echo "------------------------------------------------------------------------------------------------------"
echo "exec: executes a process without forking a new process"
echo "------------------------------------------------------------------------------------------------------"
echo "ps -C is similar as pgrep: used to find pid associated with command"
echo "------------------------------------------------------------------------------------------------------"
echo "kill command will kill the process."
echo "kill commad will send signal to the process."
echo "To list all the Signals, run (kill -l)"
echo "SIGHUP(1): kill -1 1(To re-read configuration file)"
echo "SIGTERM(15): Default signal; kill 4232"
echo "SIGKILL(9): Kill the process; It will send signal to kernel and not to the process; kill -9 5342"
echo "Locate a process using top command: top--> L ----> command-name"
echo "------------------------------------------------------------------------------------------------------"
